spring:
  application:
    name: gateway
security:
  basic:
    enabled: false
management:
  security:
    enabled: false    

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
          
zuul:
  ignored-headers: X-none
  ignore-security-headers: false
  routes:
    spm:
      path: /spm/**
      serviceId: participant-management
    pam:
      path: /pam/**
      serviceId: accounts
    acm:
      path: /acm/**
      serviceId: account-contrib
    plan:
      path: /plan/**
      serviceId: plan
---
spring.profiles: cloud
eureka:
  instance:
    nonSecurePort: 80
    hostname: ${vcap.application.uris[0]}

---
spring.profiles: default
eureka:
  client:
    enabled: false


ribbon:
  eureka:
    enabled: false

plan:
  ribbon:
    #listOfServers: localhost:8999
    listOfServers: plan-ipm-cts.cfapps.io

participant-management:
  ribbon:
    #listOfServers: localhost:9000
    listOfServers: spm-ipm-cts.cfapps.io
    
accounts:
  ribbon:
    #listOfServers: localhost:9001
    listOfServers: pam-ipm-cts.cfapps.io
    
    
account-contrib:
  ribbon:
    #listOfServers: localhost:9002
    listOfServers: acm-ipm-cts.cfapps.io