spring:
  application:
    name: gateway
security:
  basic:
    enabled: false
management:
  security:
    enabled: false    

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
          
zuul:
  ignored-headers: X-none
  ignore-security-headers: false
  routes:
    spm:
      path: /spm/**
      serviceId: participant-management
    pam:
      path: /pam/**
      serviceId: accounts
    acm:
      path: /acm/**
      serviceId: account-contrib

---
spring.profiles: cloud
eureka:
  instance:
    nonSecurePort: 80
    hostname: ${vcap.application.uris[0]}

---
spring.profiles: deployed-eureka

zuul:
  ignored-headers: X-none
  ignore-security-headers: false
  routes:
    spm:
      path: /spm/**
      serviceId: participant-management-v1a
    pam:
      path: /pam/**
      serviceId: accounts-v1a
    acm:
      path: /acm/**
      serviceId: account-contrib-v1a



---
spring.profiles: default
eureka:
  client:
    enabled: false


ribbon:
  eureka:
    enabled: false

participant-management:
  ribbon:
    listOfServers: localhost:9000

accounts:
  ribbon:
    listOfServers: localhost:9001

account-contrib:
  ribbon:
    listOfServers: localhost:9002
