spring:
  application:
    name: gateway

---
spring.profiles: default
eureka:
  client:
    enabled: false
zuul:
  routes:
    spm:
      path: /spm/**
      serviceId: participant-management
    pam:
      path: /pam/**
      serviceId: accounts
    acm:
      path: /acm/**
      serviceId: account-contrib

ribbon:
  eureka:
    enabled: false

participant-management:
  ribbon:
    listOfServers: localhost:9000

accounts:
  ribbon:
    listOfServers: localhost:9001

account-contrib:
  ribbon:
    listOfServers: localhost:9002
