spring:
  application:
    name: gateway

---
spring.profiles: default
eureka:
  client:
    enabled: false
zuul:
  routes:
    spm:
      path: /spm/**
      serviceId: participant-management
    pam:
      path: /pam/**
      serviceId: accounts

ribbon:
  eureka:
    enabled: false

participant-management:
  ribbon:
    listOfServers: localhost:9000

accounts:
  ribbon:
    listOfServices: localhost:9001
