spring:
  application:
    name: gateway
security:
  basic:
    enabled: false

    
zuul:
  ignored-headers: X-none
  ignore-security-headers: false
  routes:
    spm:
      path: /spm/**
      serviceId: participant-management
    pam:
      path: /pam/**
      serviceId: accounts
    acm:
      path: /acm/**
      serviceId: account-contrib

---
spring.profiles: default
eureka:
  client:
    enabled: false


ribbon:
  eureka:
    enabled: false

participant-management:
  ribbon:
    listOfServers: localhost:9000

accounts:
  ribbon:
    listOfServers: localhost:9001

account-contrib:
  ribbon:
    listOfServers: localhost:9002
