spring:
  application:
    name: accounts
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
security:
  basic:
    enabled: false

    
sub:
  dlx: pam-dlx

plan:
  sub:
    plan-exchange: plan-exchange
    queues:
      publish: pam-plan-publish

participant:
  sub:
    participant-exchange: participant-exchange
    queues:
      participant-added: pam-participant-added
      participant-enrolled: pam-participant-enrolled

logging:
  level:
    com.cognizant : DEBUG
---
spring.profiles: default
eureka:
  client:
    enabled: false
server:
  port: 9001
  
ribbon:
  eureka:
    enabled: false

account-contrib:
  ribbon:
    listOfServers: localhost:9002

fund:
  ribbon:
    listOfServers: localhost:9010    

