spring:
  application:
    name: accounts
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
security:
  basic:
    enabled: false
management:
  security:
    enabled: false    

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
          
sub:
  dlx: pam-dlx

plan:
  sub:
    plan-exchange: plan-exchange
    queues:
      publish: pam-plan-publish

participant:
  sub:
    participant-exchange: participant-exchange
    queues:
      participant-added: pam-participant-added
      participant-enrolled: pam-participant-enrolled

app:
  name:
    account-contrib: account-contrib
    fund: fund

logging:
  level:
    com.cognizant : DEBUG
---
spring.profiles: cloud
eureka:
  instance:
    nonSecurePort: 80
    hostname: ${vcap.application.uris[0]}

  
---
spring.profiles: default
eureka:
  client:
    enabled: false
server:
  port: 9001
  
ribbon:
  eureka:
    enabled: false

account-contrib:
  ribbon:
    listOfServers: localhost:9002

fund:
  ribbon:
    listOfServers: localhost:9010    

---
spring.profiles: standalone-eureka

app:
  name:
    account-contrib: account-contrib-v1a
    fund: fund-v1a