server:
  port: 9010
spring:
  application:
    name: fund
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
      
logging:
  level:
    org: WARN 
    com.netflix: WARN 
    com.cognizant : DEBUG    
            
security:
  basic:
    enabled: false      
management:
  security:
    enabled: false
---
spring.profiles: cloud
eureka:
  instance:
    nonSecurePort: 80
    hostname: ${vcap.application.uris[0]}

---
spring.profiles: default
eureka:
  client:
    enabled: false
