server:
  port: 9010
spring:
  application:
    name: fund
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
security:
  basic:
    enabled: false      
---
spring.profiles: default
eureka:
  client:
    enabled: false
