spring:
  application:
    name: participant-management
  jackson:
    serialization:
      write_dates_as_timestamps: false 
      
exchanges:
  sponsor: sponsor-exchange
  participant: participant-exchange

sponsor:
  pub:
    exchange: sponsor-exchange

participant:
  pub:
    exchange: participant-exchange
 
plan:
  sub:
    plan-exchange: plan-exchange
    queues:
      publish: spm-publish-queue
  
security:
  basic:
    enabled: false
logging:
  level:
    com.cognizant : DEBUG
---
spring.profiles: default
server:
  port: 9000
eureka:
  client:
    enabled: false
    
