spring:
  application:
    name: participant-management
  jackson:
    serialization:
      write_dates_as_timestamps: false 
      
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
     
exchanges:
  sponsor: sponsor-exchange
  participant: participant-exchange

sponsor:
  pub:
    exchange: sponsor-exchange

participant:
  pub:
    exchange: participant-exchange
 
plan:
  sub:
    plan-exchange: plan-exchange
    queues:
      publish: spm-publish-queue


management:
  security:
    enabled: false
security:
  basic:
    enabled: false
logging:
  level:
    com.cognizant : DEBUG
---
spring.profiles: cloud
eureka:
  instance:
    nonSecurePort: 80
    hostname: ${vcap.application.uris[0]}


---
spring.profiles: default
server:
  port: 9000
eureka:
  instance:
    nonSecurePort: 80


#eureka:
#  client:
#    enabled: false
    
