server:
  port: 8999

  
security:
  basic:
    enabled: false

logging:
  level:
    com.cognizant : DEBUG
    
sync:
  amqp:
    plan:
      exchange: plan-exchange
    account:
      exchange: account-exchange

eureka:
  instance:
    nonSecurePort: 80
    hostname: ${vcap.application.uris[0]}
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

management:
  security:
    enabled: false
      
---
spring.profiles: default
debug: true
spring:
  jpa:
    database: H2