server:
  port: 8999

  
security:
  basic:
    enabled: false

logging:
  level:
    com.cognizant : DEBUG
    
sync:
  amqp:
    plan:
      exchange: plan-exchange
    account:
      exchange: account-exchange
      
---
spring.profiles: default
debug: true
spring:
  jpa:
    database: H2