spring:
  application:
    name: account-contrib
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

security:
  basic:
    enabled: false
management:
  security:
    enabled: false    

sub:
  dlx: acm-dlx

plan:
  sub:
    plan-exchange: plan-exchange
    queues:
      publish: acm-plan-publish

participant:
  sub:
    participant-exchange: participant-exchange
    queues:
      participant-added: acm-participant-added
      participant-enrolled: acm-participant-enrolled

logging:
  level:
    com.cognizant : DEBUG

---
spring.profiles: cloud
eureka:
  instance:
    nonSecurePort: 80
    hostname: ${vcap.application.uris[0]}


---
spring.profiles: default
eureka:
  client:
    enabled: false
server:
  port: 9002
