spring:
  application:
    name: account-contrib

security:
  basic:
    enabled: false

sub:
  dlx: acm-dlx

plan:
  sub:
    plan-exchange: plan-exchange
    queues:
      publish: acm-plan-publish

participant:
  sub:
    participant-exchange: participant-exchange
    queues:
      participant-added: acm-participant-added
      participant-enrolled: acm-participant-enrolled

logging:
  level:
    com.cognizant : DEBUG
---
spring.profiles: default
eureka:
  client:
    enabled: false
server:
  port: 9002
